apiVersion: v1
kind: Service
metadata:
  name: reproserver-web-prod
  labels:
    app: reproserver
    tier: prod
spec:
  selector:
    app: reproserver
    repro-pod: web
    tier: prod
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: reproserver-s3-prod
  labels:
    app: reproserver
    tier: prod
spec:
  selector:
    app: reproserver
    repro-pod: minio
    tier: prod
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    nodePort: 30090
